package com.demo.bean;

public class Answer extends AnswerKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.AnswerContent
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    private String answerContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.AnswerTrue
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    private Boolean answerTrue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.AnswerContent
     *
     * @return the value of answer.AnswerContent
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public String getAnswerContent() {
        return answerContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.AnswerContent
     *
     * @param answerContent the value for answer.AnswerContent
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public void setAnswerContent(String answerContent) {
        this.answerContent = answerContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.AnswerTrue
     *
     * @return the value of answer.AnswerTrue
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public Boolean getAnswerTrue() {
        return answerTrue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.AnswerTrue
     *
     * @param answerTrue the value for answer.AnswerTrue
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public void setAnswerTrue(Boolean answerTrue) {
        this.answerTrue = answerTrue;
    }
}