package com.demo.bean;

public class QuestionresultKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionresult.QuestionResultId
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    private Integer questionResultId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionresult.TestResultId
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    private Integer testResultId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionresult.QuestionResultId
     *
     * @return the value of questionresult.QuestionResultId
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public Integer getQuestionResultId() {
        return questionResultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionresult.QuestionResultId
     *
     * @param questionResultId the value for questionresult.QuestionResultId
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public void setQuestionResultId(Integer questionResultId) {
        this.questionResultId = questionResultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionresult.TestResultId
     *
     * @return the value of questionresult.TestResultId
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public Integer getTestResultId() {
        return testResultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionresult.TestResultId
     *
     * @param testResultId the value for questionresult.TestResultId
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public void setTestResultId(Integer testResultId) {
        this.testResultId = testResultId;
    }
}