package com.demo.bean;

public class Questionresult extends QuestionresultKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionresult.QuestionResultAnswer
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    private String questionResultAnswer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionresult.QuestionResultAnswer
     *
     * @return the value of questionresult.QuestionResultAnswer
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public String getQuestionResultAnswer() {
        return questionResultAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionresult.QuestionResultAnswer
     *
     * @param questionResultAnswer the value for questionresult.QuestionResultAnswer
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public void setQuestionResultAnswer(String questionResultAnswer) {
        this.questionResultAnswer = questionResultAnswer;
    }
}