package com.demo.bean;

public class Question extends QuestionKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.QuestionContent
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    private String questionContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.AnswerId
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    private Integer answerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.Point
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    private Integer point;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.QuestionContent
     *
     * @return the value of question.QuestionContent
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public String getQuestionContent() {
        return questionContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.QuestionContent
     *
     * @param questionContent the value for question.QuestionContent
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public void setQuestionContent(String questionContent) {
        this.questionContent = questionContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.AnswerId
     *
     * @return the value of question.AnswerId
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public Integer getAnswerId() {
        return answerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.AnswerId
     *
     * @param answerId the value for question.AnswerId
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public void setAnswerId(Integer answerId) {
        this.answerId = answerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.Point
     *
     * @return the value of question.Point
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public Integer getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.Point
     *
     * @param point the value for question.Point
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public void setPoint(Integer point) {
        this.point = point;
    }
}