package com.demo.bean;

public class TestresultKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testresult.TestResultId
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    private Integer testResultId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testresult.UserId
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testresult.TestResultId
     *
     * @return the value of testresult.TestResultId
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public Integer getTestResultId() {
        return testResultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testresult.TestResultId
     *
     * @param testResultId the value for testresult.TestResultId
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public void setTestResultId(Integer testResultId) {
        this.testResultId = testResultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testresult.UserId
     *
     * @return the value of testresult.UserId
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testresult.UserId
     *
     * @param userId the value for testresult.UserId
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}