package com.demo.bean;

public class Testresult extends TestresultKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testresult.TestId
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    private Integer testId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testresult.Point
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    private Integer point;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testresult.TestId
     *
     * @return the value of testresult.TestId
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public Integer getTestId() {
        return testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testresult.TestId
     *
     * @param testId the value for testresult.TestId
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public void setTestId(Integer testId) {
        this.testId = testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testresult.Point
     *
     * @return the value of testresult.Point
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public Integer getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testresult.Point
     *
     * @param point the value for testresult.Point
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public void setPoint(Integer point) {
        this.point = point;
    }
}