package com.demo.bean;

public class Test {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.TestId
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    private Integer testId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.TestName
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    private String testName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.SumPoint
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    private Integer sumPoint;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.TestId
     *
     * @return the value of test.TestId
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public Integer getTestId() {
        return testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.TestId
     *
     * @param testId the value for test.TestId
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public void setTestId(Integer testId) {
        this.testId = testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.TestName
     *
     * @return the value of test.TestName
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public String getTestName() {
        return testName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.TestName
     *
     * @param testName the value for test.TestName
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public void setTestName(String testName) {
        this.testName = testName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.SumPoint
     *
     * @return the value of test.SumPoint
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public Integer getSumPoint() {
        return sumPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.SumPoint
     *
     * @param sumPoint the value for test.SumPoint
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public void setSumPoint(Integer sumPoint) {
        this.sumPoint = sumPoint;
    }
}