package com.demo.bean;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.UserId
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.UserName
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Password
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Phone
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Email
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Address
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Role
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    private String role;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.UserId
     *
     * @return the value of user.UserId
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.UserId
     *
     * @param userId the value for user.UserId
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.UserName
     *
     * @return the value of user.UserName
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.UserName
     *
     * @param userName the value for user.UserName
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Password
     *
     * @return the value of user.Password
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Password
     *
     * @param password the value for user.Password
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Phone
     *
     * @return the value of user.Phone
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Phone
     *
     * @param phone the value for user.Phone
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Email
     *
     * @return the value of user.Email
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Email
     *
     * @param email the value for user.Email
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Address
     *
     * @return the value of user.Address
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Address
     *
     * @param address the value for user.Address
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Role
     *
     * @return the value of user.Role
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Role
     *
     * @param role the value for user.Role
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public void setRole(String role) {
        this.role = role;
    }
}