package com.demo.bean;

public class UsertestKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertest.TestId
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    private Integer testId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertest.UserId
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertest.UserTestId
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    private Integer userTestId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertest.TestId
     *
     * @return the value of usertest.TestId
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public Integer getTestId() {
        return testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertest.TestId
     *
     * @param testId the value for usertest.TestId
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public void setTestId(Integer testId) {
        this.testId = testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertest.UserId
     *
     * @return the value of usertest.UserId
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertest.UserId
     *
     * @param userId the value for usertest.UserId
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertest.UserTestId
     *
     * @return the value of usertest.UserTestId
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public Integer getUserTestId() {
        return userTestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertest.UserTestId
     *
     * @param userTestId the value for usertest.UserTestId
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    public void setUserTestId(Integer userTestId) {
        this.userTestId = userTestId;
    }
}