package com.demo.dao;

import com.demo.bean.Answer;
import com.demo.bean.AnswerKey;

public interface AnswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    int deleteByPrimaryKey(AnswerKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    int insert(Answer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    int insertSelective(Answer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    Answer selectByPrimaryKey(AnswerKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    int updateByPrimaryKeySelective(Answer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    int updateByPrimaryKey(Answer record);
}