package com.demo.dao;

import com.demo.bean.Testresult;
import com.demo.bean.TestresultKey;

public interface TestresultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testresult
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    int deleteByPrimaryKey(TestresultKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testresult
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    int insert(Testresult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testresult
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    int insertSelective(Testresult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testresult
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    Testresult selectByPrimaryKey(TestresultKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testresult
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    int updateByPrimaryKeySelective(Testresult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testresult
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    int updateByPrimaryKey(Testresult record);
}