package com.demo.dao;

import com.demo.bean.UsertestKey;

public interface UsertestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertest
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    int deleteByPrimaryKey(UsertestKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertest
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    int insert(UsertestKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertest
     *
     * @mbggenerated Thu May 05 15:29:37 ICT 2016
     */
    int insertSelective(UsertestKey record);
}